### ISSUE TITLE
Fixed Some Issue

### ISSUE THREAD

**Issue by franklinAnozie** [GavinLonDigital/TeamMemberAllocationApp#1]
Hi, Gavin. I watched your video and enjoyed it. I tried making the app on my own with great success. However, i implemented the useContext variation a lot different from what you have. I think it'll be great if you had a look.

Here's a link to my version: https://github.com/franklinAnozie/team_allocation_app

It would be nice to get feedback. Thanks.

Best Regards.
Franklin.

**Comment by GavinLonDigital** [comment]
Hi Franklin,

Thanks for your feedback :)

I'm glad you enjoyed the video, and I think it's great that you created the
app with success on your own. I'll try to have a look at your code this
week, and if I have any feedback that I think may be helpful to you, I'll
get back to you with my feedback. :)

Kind regards,
Gavin

**Comment by franklinAnozie** [comment]
Hi Gavin. Thanks for the reply.

I'll be looking forward to your feedback.
